version: "3"
name: fplms
networks:
  fplms_network:
    driver: bridge
services:
  fplms_db:
    container_name: mysql
    image: mysql:8.0.30
    ports:
      - 3306:3306
    networks:
      - fplms_network
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_DATABASE: fplms_management
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
